language: java
jdk:
  - oraclejdk8

before_script:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - npm install -g angular-cli
  - npm install -g karma
  - npm install
  - ng build

after_success:
  - bash <(curl -s https://codecov.io/bash)